SELECT DISTINCT H.HACKER_ID, H.NAME
FROM HACKERS H
LEFT OUTER JOIN CHALLENGES C
ON H.HACKER_ID = C.HACKER_ID
LEFT OUTER JOIN DIFFICULTY D
ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
LEFT OUTER JOIN SUBMISSIONS S
ON C.CHALLENGE_ID = S.CHALLENGE_ID
WHERE S.SCORE = D.SCORE
ORDER BY H.HACKER_ID;

SELECT H.HACKER_ID, H.NAME
FROM HACKERS H
LEFT OUTER JOIN CHALLENGES C
ON H.HACKER_ID = C.HACKER_ID
LEFT OUTER JOIN DIFFICULTY D
ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
LEFT OUTER JOIN SUBMISSIONS S
ON C.CHALLENGE_ID = S.CHALLENGE_ID
WHERE S.SCORE = D.SCORE
ORDER BY H.HACKER_ID;

SELECT H.HACKER_ID, H.NAME
FROM HACKERS H
LEFT OUTER JOIN CHALLENGES C
ON H.HACKER_ID = C.HACKER_ID
LEFT OUTER JOIN DIFFICULTY D
ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
LEFT OUTER JOIN SUBMISSIONS S
ON C.CHALLENGE_ID = S.CHALLENGE_ID AND S.SCORE = D.SCORE
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(S.HACKER_ID) > 1
ORDER BY COUNT(S.HACKER_ID) DESC, S.HACKER_ID ASC;